language: java
jdk:
- oraclejdk8
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && (cd powerunit-eclipse && mvn clean install site -Psite --settings ../target/travis/settings.xml)'
env:
  global:
    secure: n7rmeqEoeMvWPtzzSuWNEqwdSz4vZBRvU39FkOC9Ov4qQBEoeJgbrGYq+u1BowPYetN2KUn43hqRy4N6npo5vLQihKwE1rnKqC2xQm8fqf/F5QIeWuLREDnmAa5Ds7xIfrpU+sJrQz8BVRrYY5ihjwGsqgX0Fp+FFOmSSALXmnA=
