language: java
jdk:
- oraclejdk8
before_install: git clone -b travis `git config --get remote.origin.url` target/travis
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && (cd powerunit-eclipse && mvn clean install site -Psite --settings ../target/travis/settings.xml)'
env:
  global:
    secure: xm6WCXJpG99CmCrYgCPfZdDV7ceFkf0ZpZV8nsXWzwNhut8jw13unVe9l/z8tn+EKigtHbkCxWKLSmoFnKQwz46vlYdCFAuEvnBcfDueWuxQSLgV6S1ri2xyAMmcaoVimG93hkZKDA6mjXfAxRekSZP94ikoRm50LJMEn9TKzPw=
